{{- if or (eq "dev" .Values.global.deckhouseVersion) (semverCompare ">=1.64" .Values.global.deckhouseVersion) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-scheduler-extender
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-local-volume-scheduler-extender" )) | nindent 2 }}
spec:
  type: ClusterIP
  ports:
    - port: 8099
      targetPort: 8099
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-scheduler-extender
{{- end }}
